/**
 * Storage Schema - re-exports from @rockhounding/shared
 */
export {
  EvictionPolicy,
  StorageEntityType,
  StorageMetadataSchema,
  type StorageMetadata,
  CachedEntitySchema,
  type CachedEntity,
  CachedFieldSessionSchema,
  type CachedFieldSession,
  CachedFindLogSchema,
  type CachedFindLog,
  CachedSpecimenSchema,
  type CachedSpecimen,
  CachedCaptureSessionSchema,
  type CachedCaptureSession,
  CachedRawCaptureSchema,
  type CachedRawCapture,
  CachedProcessedCaptureSchema,
  type CachedProcessedCapture,
  CachedStorageLocationSchema,
  type CachedStorageLocation,
  CachedCollectionGroupSchema,
  type CachedCollectionGroup,
  CachedTagSchema,
  type CachedTag,
  CachedAnalyticsCacheSchema,
  type CachedAnalyticsCache,
  CachedTelemetryEventSchema,
  type CachedTelemetryEvent,
  CachedSyncQueueItemSchema,
  type CachedSyncQueueItem,
  StorageConfigSchema,
  type StorageConfig,
  StorageStatsSchema,
  type StorageStats,
  StorageHealthSchema,
  type StorageHealth,
  getSerializationRules,
  generateStorageKey,
  parseStorageKey,
  calculateTTLExpiry,
  isExpired,
  isStale,
  computeChecksum,
  verifyChecksum,
  DEFAULT_TTL_MS,
  SYNC_QUEUE_TTL_MS,
  TELEMETRY_TTL_MS,
  ANALYTICS_CACHE_TTL_MS,
  THUMBNAIL_TTL_MS,
  MAX_STORAGE_SIZE_BYTES,
  MAX_SINGLE_ENTITY_SIZE_BYTES,
  COMPACTION_THRESHOLD_BYTES,
} from '@rockhounding/shared';
